/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import { Scene } from "laya/display/Scene";
import { ClassUtils } from "laya/utils/ClassUtils";
var REG: Function = ClassUtils.regClass;
import { Image } from "laya/ui/Image";
import { Label } from "laya/ui/Label";
export module ui.loading {
	export class LoadingUI extends Scene {
		public referenceClass:Array<any>=[Image, Label]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
}
import { Box } from "laya/ui/Box";
import { Text } from "laya/display/Text";
import { Sprite } from "laya/display/Sprite";
import { Button } from "laya/ui/Button";
import { List } from "laya/ui/List";
export module ui.main {
	export class MainGameUI extends Scene {
		public referenceClass:Array<any>=[Image, Box, Text, Sprite, Button, 
				Label, List]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
}
export module ui.test {
    export class TestSceneUI extends Scene {
		public scoreLbl:Label;
		public tipLbll:Label;
        public referenceClass:Array<any>=[Label, Sprite]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}