/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import LoadingScene from "./script/scene/LoadingScene"
import MainGameScene from "./script/scene/MainGameScene"
import ButtonRunTime from "./script/tool/ButtonRunTime"
import FontGrid from "./script/prefeb/FontGrid"
import GameUI from "./script/GameUI"
import GameControl from "./script/GameControl"
import GameResult from "./script/prefeb/GameResult"
import GameSetting from "./script/prefeb/GameSetting"
import StartGame from "./script/prefeb/StartGame"
import TipItem from "./script/prefeb/TipItem"
import { Text } from "laya/display/Text"
import { BoxCollider } from "laya/physics/BoxCollider"
import { RigidBody } from "laya/physics/RigidBody"
import { ClassUtils } from "laya/utils/ClassUtils";
import { ui } from "./ui/layaMaxUI";
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="showall";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="loading/Loading.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = ClassUtils.regClass;
		reg("ui", ui);
        reg("script/scene/LoadingScene.ts",LoadingScene);
        reg("script/scene/MainGameScene.ts",MainGameScene);
        reg("script/tool/ButtonRunTime.ts",ButtonRunTime);
        reg("script/prefeb/FontGrid.ts",FontGrid);
        reg("script/GameUI.ts",GameUI);
        reg("script/GameControl.ts",GameControl);
        reg("script/prefeb/GameResult.ts",GameResult);
        reg("script/prefeb/GameSetting.ts",GameSetting);
        reg("script/prefeb/StartGame.ts",StartGame);
        reg("script/prefeb/TipItem.ts",TipItem);
        reg("Laya.Text",Text);
        reg("Laya.BoxCollider",BoxCollider);
        reg("Laya.RigidBody",RigidBody);
    }
}
GameConfig.init();